version: "3"
services:
  backend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.backend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 0.5GB
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    command: npm start
  frontend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 0.5GB
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
